### ISSUE TITLE
Support ~6.0?

### ISSUE THREAD

**Issue by morrislaptop** [gh640/phpunit-tap#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for gh640/phpunit-tap ^1.0 -> satisfiable by gh640/phpunit-tap[1.0.0].
    - gh640/phpunit-tap 1.0.0 requires phpunit/phpunit ^5.7 -> satisfiable by phpunit/phpunit[5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by gh640** [comment]
Your PR #2 has been merged. Thanks 😃
