### ISSUE TITLE
Number of assertions are not displaying

### ISSUE THREAD

**Issue by mitquinn** [gh640/phpunit-tap#6]
I am not sure why but the number of assertions are not displaying in the final tally (last line) of the output. 

`
Time: 109 ms, Memory: 12.00MB

OK (15 tests, 0 assertions)
`

It seems to be happening in the gif of the repo as well.

This is a great package by the way thanks for all of your work!

**Comment by gh640** [comment]
Thank you for reporting the issue. Surely it's wrong.

I tried fixing it in a branch `6-fix_wrong_number_assersions`. It seems to work well in my environment. Can you please try it or the PR #7 ? I'll merge it into `master` after you've confirmed.

**Comment by mitquinn** [comment]
Fixed In PR #7

**Comment by gh640** [comment]
I made a new version `3.0.2` after fixing this issue. Thanks :)
